### ISSUE TITLE
[bug] deepmerge实现需要判断target是否有[key]属性

### ISSUE THREAD

**Issue by chenhebing** [ice-lab/spec#13]
![image](https://user-images.githubusercontent.com/12512045/78664549-d47dcb80-7906-11ea-8784-d2b1bf95253a.png)

需要做下 target[key]的undefined判断， 没有的话，也走最后一个分支

**Comment by fyangstudio** [comment]
已修复，可使用 @iceworks/spec 。感谢反馈
