### ISSUE TITLE
stylelint 和 eslint 放在dependencies

### ISSUE THREAD

**Issue by chenhebing** [ice-lab/spec#15]
stylelint-config-rational-order 的 stylelint的版本依赖偏低，导致stylelint报 Undefined rule unicode-bom

请教eslint和stylelint放在dependencies依赖中

![image](https://user-images.githubusercontent.com/12512045/85915587-6ef10980-b87b-11ea-89a7-31fce0cde75a.png)

![image](https://user-images.githubusercontent.com/12512045/85915608-8e883200-b87b-11ea-9430-08a02c038812.png)

![image](https://user-images.githubusercontent.com/12512045/85915620-acee2d80-b87b-11ea-88ec-37168eff7169.png)

**Comment by fyangstudio** [comment]
已修复此问题，可使用 @iceworks/spec 。 感谢反馈
