### ISSUE TITLE
是否可以为spec提供d.ts

### ISSUE THREAD

**Issue by rainmanhhh** [ice-lab/spec#29]
### 问题描述/Problem Description

是否可以为spec提供d.ts？getPrettierConfig之类的函数第二个参数都无法自动补全

**Comment by fyangstudio** [comment]
感谢您的建议，这是个非常棒的想法。  我们会尽快投入支持 👍

**Comment by fyangstudio** [comment]
由于 spec 不依赖 prettier， spec 内部 type 申明可能会对不上上层安装的版本，包括 eslint 各项配置。

这里可能还是建议参考文档 做简单配置 比较好
