### ISSUE TITLE
eslint 规则报错应该返回具体的错误位置

### ISSUE THREAD

**Issue by muzea** [ice-lab/spec#32]
https://github.com/ice-lab/spec/blob/7f8cb174f68ca9008ade0cb9e2236b2862a5fefc/packages/eslint-plugin-best-practices/src/rules/no-js-in-ts-project.js#L36-L51

**Comment by fyangstudio** [comment]
期望是 第一行 第一个字符吗

**Comment by muzea** [comment]
期望是实际 `ImportDeclaration`/`require` 的位置，不应该是一个写死的位置。

**Comment by fyangstudio** [comment]
这个可以讨论下。import 和 require 可以不写文件类型，检测 import 文件和目前的方案项目相比，稳定性和复杂度可能目前的方案好些
