### ISSUE TITLE
脚手架去除 prettier ，统一使用 ESLint 进行格式化

### ISSUE THREAD

**Issue by fyangstudio** [ice-lab/spec#43]
## 背景

在最佳实践 [spec](https://www.npmjs.com/package/@iceworks/spec) 的 ESLint 配置中，我们已经集成了大量格式化规则。可以解决约 90% 的格式问题。

运行 ESLint 检测已成为 CI 及用户开发习惯中的一部分。

## 问题

脚手架工程同时集成 prettier 和 ESLint ，不但功能有重复，增加概念和配置，也会产生一定的使用和理解成本。

不断的迭代的 ESLint 和 prettier ，需要开发者不断解决 ESLint 和 prettier 的冲突问题，产生很大的维护成本。
（**现阶段已解决，但存在隐患**）

## 建议

秉承简单易用原则，建议脚手架工程主要推荐 ESLint 修复链路，淡化 prettier 。

**Comment by fyangstudio** [comment]
## VS Code 行为
VS Code 默认是通过 prettier 格式化的，同时用户可以不用配置 prettier 。
非常赞同这个选择，专业的事情交给专业的库， ESLint 格式化需要配置一堆规则。

## 我推荐的最佳实践
用户安装 ESLint 插件，开启 format on save 。这样每次保存文件不但能享受格式化同时修复 ESLint 问题。

回头看这2个链路，其实用户都不用关心 prettier 的配置是什么，甚至没有感受到 prettier 的存在

**Comment by imsobear** [comment]
推荐操作：

1. 将 eslint 设置为 VS Code 的一个 Formatter

![image](https://user-images.githubusercontent.com/2505411/118241652-fb75dc00-b4ce-11eb-9c03-fc33bf135e1a.png)

~~2. 右键选择「格式化文档的方式」-> 配置默认格式化 -> ESLint（一般默认是 Prettier）~~

![image](https://user-images.githubusercontent.com/2505411/118242188-a4243b80-b4cf-11eb-9343-4d9905258dc1.png)

3. VS Code 里默认开启 Format On Save

![image](https://user-images.githubusercontent.com/2505411/118242282-bdc58300-b4cf-11eb-80e3-d24bdc03ad2a.png)

**Comment by imsobear** [comment]
结论：

- VS Code 默认的 Format 配置成 ESLint 不合理（还是建议 Prettier），因为 ESLint 依赖的环境更多（比如全局或者项目必须依赖并安装 eslint），相对来说开发者使用成本高、失败率高
- 项目需要保留 Prettier 的配置文件，用来更改 prettier 默认规则以保证跟 eslint 规则一致，比如双引号改为单引号
- 推荐开启 VS Code 的 Format On Save 选项，默认用 Prettier，可以自动格式化一些基础问题（但不会覆盖 eslint 规则）
- 如果 on save 的时候希望自动修复 eslint 错误，需要配置：

```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
}
```

**Comment by fyangstudio** [comment]
ESLint 插件修复链路， 脚手架工程的 .vscode 文件可以设置掉。

```json
// .vscode/settings.json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
}

```

可以讨论下 这个配置问题，或者还可以增加更多配置 @alvinhui
