### ISSUE TITLE
getESLintConfig 增加小程序类型的属性

### ISSUE THREAD

**Issue by cryzzchen** [ice-lab/spec#45]
目前 getESLintConfig 的入参仅跟框架语言有关，例如 rax, react, rax-ts 等。
当业务使用 rax 框架开发小程序时，需要检测小程序平台的 rule。
例如编译时语法需要满足 [约束](https://rax.alibaba-inc.com/docs/guide/compile-miniapp-syntax-constraints)，对应的插件为：https://github.com/raxjs/miniapp/tree/master/packages/eslint-plugin-rax-compile-time-miniapp

目前有两个方案：
1. 在运行 spec 时，检测仓库中的 build.json，读取 targets 和 target 对应的 buildType，来自动加载对应插件；
2. 在初始化仓库时，根据类型，在仓库的 .eslintrc.js 中声明当前仓库的类型

方案一：与 rax 仓库的目录结构高耦合，若业务方的脚手架进行过封装可能会失效。
方案二：若仓库初始化完成后，用户修改了 targets 和 target 对应的 buildType，那么 .eslintrc.js 也需要修改配置。

**Comment by fyangstudio** [comment]
#46
