### ISSUE TITLE
@iceworks/eslint-plugin-best-practices 性能问题

### ISSUE THREAD

**Issue by nanokind** [ice-lab/spec#50]
包名: @iceworks/eslint-plugin-best-practices

## 您的本地环境信息/Your local environment information

* 操作系统及其版本/System and Version: MacOS
* Node version: v14.17.0
* 问题 npm 包 version: 0.2.7

## 您遇到的问题及复现步骤/What are your problems and how to reproduce them

这个包依赖了 @mdn/browser-compat-data@^2.0.3，这个版本的 @mdn/browser-compat-data 有比较严重的性能问题（包含了很多同步的 fs 调用），同时体积也比较大（22 MB），新版本 @mdn/browser-compat-data@4.x 发布前做了预打包处理，性能更好，而且体积只有 9.6MB

在 slow HDD 上的性能数据：

```
老版本：>4s
新版本：<1s
```

性能数据参考：[Publish pre-build bundles to npm](https://github.com/mdn/browser-compat-data/issues/7374)

## 您期待的正确结果/The right result you're looking forward to

升级至 @iceworks/eslint-plugin-best-practices 的依赖 @mdn/browser-compat-data 到 4.x 版本，解决性能问题，同时减少 npm install 时间

@fyangstudio

**Comment by fyangstudio** [comment]
好的 感谢反馈。  1.5.0 发版后，会合并
